### ISSUE TITLE
Error: Cannot find module '../../lib/aid'

### ISSUE THREAD

**Issue by jarrodldavis** [kristianmandrup/ember-config#1]
I run `yo ember-config` from the root of the freshly generated Ember CLI app and this error occurs:

```
Error: Cannot find module '../../lib/aid'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-ember-config/generators/app/index.js:6:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by lancedikson** [comment]
I have the same issue:

```
Error: Cannot find module '../../lib/aid'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-ember-config/generators/app/index.js:6:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by kristianmandrup** [comment]
Fork, fix and forget... ;)

**Comment by kristianmandrup** [comment]
Tried to fix this, but unable to run any `npm` command at this point, such as `npm link` or `npm install`:

```
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'
```

Upgraded to iojs 1.6.4 and latest nvm etc. but still no luck. Also tried flexing all dependencies of `ember-config` in `package.json` ... Any ideas? Haven't worked with nodejs in a while :P

```
  "dependencies": {
    "sync": "x",
    "chalk": "x",
    "fs-extra": "x",
    "glob": "x",
    "string": "x",
    "sugar": "x",
    "bower-directory": "x",
    "string-mutator": "x",
    "yeoman-generator": "x",
    "yosay": "x",
    "yo": ">=1.0.0"
  },
  "devDependencies": {
    "mocha": "*"
  }
```

**Comment by kristianmandrup** [comment]
This project needs a loving hand. The `lib/aid` file needs to be split up in smaller logical modules etc.
Please help out ;)

**Comment by lancedikson** [comment]
I'll try to checkout project. First I would like to take a look at the goal of this project, but can't to run it. Will try to fix the problem and contribute if it will be helpful for me or community :)

**Comment by kristianmandrup** [comment]
Problem turns out to be in a very unsuspected, innocent looking place:
Had a similar problem with my recent aurelia generator...

https://github.com/kristianmandrup/generator-aurelia-ts/issues/11#issuecomment-130212445

It turned out it was due to a `package.json` setting `files:` which points to `generators` as the place with all the files.  However since `/lib` is outside the `/generators` folder (so as not to be picked up as a generator), it was inaccessible since not part of files when installed by npm! Doh :O. 
Tested and works now, both via npm link and global install. Finally :)
